console.log("Welcome to the Area and Perimeter Calculator\n");
console.log("Enter length: ");
console.log("Enter width: ");
let length = 100;
let width = 200;
let area = length * width;
let perimeter = (2*length) + (2*width);
console.log("Area:      "+area);
console.log("Perimeter:   "+perimeter);
console.log("\nContinue? (y/n): \n");